---
- name: 'Create compose file: {{ chat2bridge_cont_name }}'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ chat2bridge_compose_file }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create container: {{ chat2bridge_cont_name }}'
  docker_compose:
    project_src: '{{ chat2bridge_service_path }}'
    pull: true
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate }}'
    # Avoid deprecation warning
    tls_hostname: 'localhost'
